### ISSUE TITLE
Post latest release on pypi

### ISSUE THREAD

**Issue by hiccup7** [altendky/pyqt5-tools#1]
Any reason why dev10 isn't at https://pypi.python.org/pypi/pyqt5-tools ?

**Comment by altendky** [comment]
PyPi wouldn't accept the large file.  :[

https://www.riverbankcomputing.com/pipermail/pyqt/2016-September/038028.html
```
I updated pyqt5-tools to include all of the .exe's from the Qt bin 
directory and also anything copied by windeployqt for each .exe.  I 
tried a couple and they ran but didn't test much more.  I'm sure you'll 
find stuff that doesn't work at all.

For the moment you can get the latest wheels from GitHub since they are 
too large for PyPi (125MB and 150MB or so and in the ballpark of 700MB 
installed).

https://github.com/altendky/pyqt5-tools/releases/tag/v5.7.dev10

At some point I'll figure out how to handle the file size and PyPi, but 
not right now.  Separate packages?  A package that just downloads and 
installs?  We'll see.

The other requests I recall are for documentation to be included and 
other platforms supported.  Probably won't get to these soon, sorry.

Cheers,
-kyle
```

**Comment by altendky** [comment]
Also, you should be able to `pip install <wheel url>` directly.  Obviously not as nice but better than manually downloading and then installing.

**Comment by altendky** [comment]
1) There are now builds on PyPi for 5.8.2 and 5.7.1 for Python 3.6 and 3.5 for both 32 and 64 bit.  Note that they are marked RC but since I have no full releases yet they should still install without using `--pre`.
2) They are missing the web engine EXEs and libs since that dropped the size from 130MB to 30MB.
