### ISSUE TITLE
Invisibles plugins ?

### ISSUE THREAD

**Issue by guilbut** [altendky/pyqt5-tools#10]
Hello,

Thank you for your pyqt5-tools ! 
I did not manage to make appear plugin examples in Qt Designer. I installed a clean python 3.6.4 , I made a pip3 install PyQt5==5.9 (to be at the same version as pyqt5-tools),and I made a pip install pyqt5-tools.I modified the examples/designer/plugins/plugins.py script to find the binary designer.
In help> plugin Information, i have an error message telling "Cannot load library ......\pyqt5-tools\plugins\designer\pyqt5.dll:  the specified module could not be found".  I'm sure that the file existe and that designer found it because when I remove it , in help> plugin Information, QtDesigner juste say "QtDesigner could'nt find any plugins". Did you manage to have plugins visible in Qt Designer?
I really need it.

Cheers,

Baptiste

**Comment by altendky** [comment]
Following up on the maillist.

https://www.riverbankcomputing.com/pipermail/pyqt/2018-February/040028.html

**Comment by altendky** [comment]
I'll keep this open until it gets released but with current builds there are more versions available.  Make sure you get the one that matches the PyQt5 and Python versions you are running.

https://ci.appveyor.com/project/KyleAltendorf/pyqt5-tools/build/575

**Comment by altendky** [comment]
There are certainly still issues with the released versions but this is old and has no followup so closing.  Please feel free to file a new bug against the new (pre) releases.

**Comment by iamrash** [comment]
ERROR: Could not find a version that satisfies the requirement pyqt5-tools (from versions: none)
ERROR: No matching distribution found for pyqt5-tools

I am using Ubuntu 18.04, python 3.7.3 and latest pip 19.1.1
i also tried to install it offline but still same error. I don't know what to do, any help will be helpful.
