### ISSUE TITLE
how to configure the language to chinese simple ?

### ISSUE THREAD

**Issue by guowujun** [altendky/pyqt5-tools#11]
who knows how to confugure qt designer appearance language to chinese simple。

**Comment by altendky** [comment]
Looks like you are supposed to set the `LANG` environment variable to `ZH_CN`.  I'm not sure where the official list is but found this one real quick.

https://www.ibm.com/support/knowledgecenter/en/SSGSG7_6.3.4/com.ibm.itsm.srv.install.doc/r_nls_tables.html

**Comment by TurboWay** [comment]
I installed pyqt5-tools through pip and encountered the same problem. How do I set up Simplified Chinese? Can you give a detailed tutorial, win7 environment, thank you very much

**Comment by altendky** [comment]
I see the above link is broken but the suggestion was to set the mentioned environment variable.  Now that this is just about designer, not pyqt at all m

**Comment by altendky** [comment]
If someone can confirm this I'd be happy to try to add it as a cli option on the `pyqt5designer` wrapper.  In the mean time it isn't actually about pyqt5-tools so I'll close this.
