### ISSUE TITLE
Custom plugin fails to load with pyqt5 5.11.3

### ISSUE THREAD

**Issue by Mac-Genius** [altendky/pyqt5-tools#22]
I'm trying to load a custom plugin into designer and pyqt5designer silently crashes when it tries to load it.

Python version: 3.6.5
pyqt5 version: 5.11.3
pyqt5_tools version: 5.11.3.1.4rc0

I also tried to run `pyqt5designer --test-exception-dialog` and that crashes silently as well.

When testing with pyqt5 version 5.11.2 it seems to work just fine.

**Comment by altendky** [comment]
Sorry for the confusion.  I don't even remember why I thought I was building for pyqt 5.11.3 then...  but yeah, that didn't really support 5.11.3, iirc, and as you noticed.  I just triggered a build for v1.4 that should push 5.11.3 support to PyPI.  Please do let me know whether it works for you or not.  Along with `--test-exception-dialog` there's `--example-widget-path` that should show a pyqt5-tools widget group and a single (pointless outside validation that the plugin is working) 'custom' button widget.

https://ci.appveyor.com/project/KyleAltendorf/pyqt5-tools/builds/21129252

**Comment by altendky** [comment]
Oh, and thanks for actually providing feedback.  I don't get a whole lot of that and I'm pretty sure it's not because the package is working perfectly... :|

**Comment by Mac-Genius** [comment]
That worked! I appreciate you taking a look at it. You're welcome for the feedback, this package is awesome and I'm glad I could help make it a little better :D
