### ISSUE TITLE
Can't install qt5 via pip

### ISSUE THREAD

**Issue by sunn-e** [altendky/pyqt5-tools#27]
I tried `pip install pyqt5-tools' It did not work. 
error message -  Could not find a version that satisfies the requirement pyqt5-tools (from versions: )
No matching distribution found for pyqt5-tools
You are using pip version 8.1.1, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by altendky** [comment]
Be sure to be working in a virtualenv or venv (https://bit.ly/py-env) but what OS are you on?  pyqt5-tools is only available on Windows (see #21).  For the latest version see #26.

**Comment by sunn-e** [comment]
I used conda on windows.

**Comment by altendky** [comment]
What do you get for `pip --version` and `pip install -v pyqt5-tools`?

**Comment by sunn-e** [comment]
while fixing the error on my own, I broke my pip. Need to look after it.

**Comment by altendky** [comment]
Were you able to get this resolved?

**Comment by meichthys** [comment]
@altendky  I believe this can be closed. I've tested the pip install without any issues.

**Comment by altendky** [comment]
This was an issue while using conda.  @meichthys, were you working with conda?  I expect at some point this will be closed as stagnant but I'm in no rush.

**Comment by meichthys** [comment]
Oh, sorry, i missed that. I wasn't using conda.

**Comment by altendky** [comment]
I'm not sure what the error was but they seemed to have fixed it for themselves.
