### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement pyqt5-tools (from versions: none) ERROR: No matching distribution found for pyqt5-tools 

### ISSUE THREAD

**Issue by iamrash** [altendky/pyqt5-tools#28]
ERROR: Could not find a version that satisfies the requirement pyqt5-tools (from versions: none) ERROR: No matching distribution found for pyqt5-tools 
I am using Ubuntu 18.04, python 3.7.3 and latest pip 19.1.1 i also tried to install it offline but still same error. I don't know what to do, any help will be helpful.

**Comment by The-Compiler** [comment]
This project is Windows only, see #21.

**Comment by meichthys** [comment]
@altendky I believe this issue can be tagged in #21 and closed.
