### ISSUE TITLE
pyqt5-tools for PyQt5.13

### ISSUE THREAD

**Issue by S-M-R-Sadeghi** [altendky/pyqt5-tools#29]
Please make a version compatible for PyQt5 version 5.13 and later.

**Comment by altendky** [comment]
I do apologize for the horrible maintenance of this project.  I'll try to get something started building this morning if I can get my phone to hotspot properly in the car this time...

**Comment by altendky** [comment]
Alrighty, v1.5 should be heading up to pypi with a new python/pyqt combo every 10 minutes or so.  Let me know if they work for you or not.

**Comment by altendky** [comment]
Release packages should be up.  Please let me know if they work for you.

**Comment by S-M-R-Sadeghi** [comment]
thank you very much for update. it works good.
