### ISSUE TITLE
PyQt5 is not installing for Python3.7 under any version

### ISSUE THREAD

**Issue by vickylance** [altendky/pyqt5-tools#30]
Hi,
I tried the below commands and none of them seems to find/install the package.

<img width="1135" alt="Screen Shot 2019-08-18 at 9 57 46 AM" src="https://user-images.githubusercontent.com/5861833/63220127-caa03000-c19e-11e9-9fd7-5967d54c21ac.png">

**Comment by The-Compiler** [comment]
This repository supports Windows only, see #21.

**Comment by vickylance** [comment]
oh I see. Thanks for the clarification
