### ISSUE TITLE
Scripts fail to run after 'freezing' with pyinstaller

### ISSUE THREAD

**Issue by meichthys** [altendky/pyqt5-tools#31]
Python: 3.7.2
pyqt5-tools: v5.13.0.1.5

When using v5.11.3.1.4 (and even in v5.12.1.1.5rc4) built exe's run fine when they are created using pyinstaller. However, after the latest version release, pyinstaller cannot seem to find the pyqt5.sip module. It seems to have something to do with the entrypoint changes to the build.py file in commit a23a36417a784e967bd1b55058572a6774852539.

For now i can run the previous version, and i understand if you would rather not look into a fix since the issue is pyinstaller related and might not be a problem for other users. If there's any other testing i can do, let me know.

**Comment by altendky** [comment]
Hmm, you are looking to pyinstaller and distribute the pyqt5-tools wrappers?  I can't promise a lot of time but you do at least have me curious.  :]

You say that v5.12.1.1.5rc4 works but not v5.13.0.1.5.  What about v5.12.3.1.5?

Share the full pyinstaller output (with -v or whatever for verbosity, I forget).  If it isn't finding the dependency to begin with then you could at least work around it by specifying a hidden import of `pyqt5.sip`.

https://github.com/altendky/pyqt5-tools/commit/a23a36417a784e967bd1b55058572a6774852539 was done as some of the new tools in 5.13 (I think) have `-`s in their names.  this is fine for an `entry_points` but not for a function name.

**Comment by meichthys** [comment]
We use pyinstaller to bundle all needed dependencies (including python interpreter) into a single exe file that we can distribute. Primarily we need to bundle pyqt, but since we like pyqt5-tools so much, we bundle that too.

I missed v5.12.3.1.5, but I just tested that, and it gives the same issue as v5.13.0.1.5

The full output of the pyinstaller command is below (I've bolded the notable messages):

The command completes 'succesfully' but the program fails with the following popup:

![image](https://user-images.githubusercontent.com/10717998/63353789-48944080-c331-11e9-9779-81b56cd866cd.png)

If I build the exe as a console application the following output is provided when it fails:

![image](https://user-images.githubusercontent.com/10717998/63354109-d1ab7780-c331-11e9-8796-0c189569d12b.png)

```
>pyinstaller
 --name ProgramName --onefile --clean --windowed --icon C:\Development\projects\programName\gui\icon.ico --distpath C:\Development\projects\ProgramName\exe\ --workpath C:\Development\projects\ProgramName\exe\ C:\Development\projects\ProgramName\main.py
91 INFO: PyInstaller: 3.5
91 INFO: Python: 3.7.2
91 INFO: Platform: Windows-10-10.0.18362-SP0
91 INFO: wrote C:\Development\projects\program-name\programname\programname.spec
94 INFO: UPX is not available.
94 INFO: Removing temporary files and cleaning cache in C:\Users\user\AppData\Roaming\pyinstaller
129 INFO: Extending PYTHONPATH with paths
['C:\\Development\\projects\\program-name\\programname',
 'C:\\Development\\projects\\program-name\\programname']
129 INFO: checking Analysis
129 INFO: Building Analysis because Analysis-00.toc is non existent
129 INFO: Initializing module dependency graph...
133 INFO: Initializing module graph hooks...
134 INFO: Analyzing base_library.zip ...
2898 INFO: running Analysis Analysis-00.toc
2901 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\development\projects\program-name\.venv\scripts\python.exe
4698 INFO: Caching module hooks...
4704 INFO: Analyzing C:\Development\projects\program-name\programname\main.py
5463 INFO: Processing pre-safe import module hook   win32com
5495 INFO: Processing pre-find module path hook   distutils
5496 INFO: distutils: retargeting to non-venv dir 'C:\\Development\\install\\python\\Lib\\distutils\\__init__.py'
6728 INFO: Processing pre-safe import module hook   urllib3.packages.six.moves
8576 INFO: Processing pre-find module path hook   site
8577 INFO: site: retargeting to fake-dir 'c:\\development\\projects\\program-name\\.venv\\lib\\site-packages\\PyInstaller\\fake-modules'
9687 INFO: Loading module hooks...
9687 INFO: Loading module hook "hook-certifi.py"...
9689 INFO: Loading module hook "hook-encodings.py"...
9781 INFO: Loading module hook "hook-lxml.etree.py"...
9783 INFO: Loading module hook "hook-pkg_resources.py"...
10339 INFO: Loading module hook "hook-pydoc.py"...
10339 INFO: Loading module hook "hook-pyodbc.py"...
10462 INFO: Loading module hook "hook-PyQt5.py"...
**10627 WARNING: Hidden import "sip" not found!**
10628 INFO: Loading module hook "hook-PyQt5.QtCore.py"...
11506 INFO: Loading module hook "hook-PyQt5.QtGui.py"...
12877 INFO: Loading module hook "hook-PyQt5.QtWidgets.py"...
15496 INFO: Loading module hook "hook-pythoncom.py"...
15753 INFO: Loading module hook "hook-pywintypes.py"...
16009 INFO: Loading module hook "hook-sysconfig.py"...
16011 INFO: Loading module hook "hook-win32com.py"...
16066 INFO: Loading module hook "hook-xml.dom.domreg.py"...
16067 INFO: Loading module hook "hook-xml.etree.cElementTree.py"...
16067 INFO: Loading module hook "hook-xml.py"...
16101 INFO: Looking for ctypes DLLs
16116 INFO: Analyzing run-time hooks ...
16121 INFO: Including run-time hook 'pyi_rth_certifi.py'
16122 INFO: Including run-time hook 'pyi_rth_pkgres.py'
16123 INFO: Including run-time hook 'pyi_rth_win32comgenpy.py'
16125 INFO: Including run-time hook 'pyi_rth_pyqt5.py'
16135 INFO: Looking for dynamic libraries
38777 INFO: Looking for eggs
38777 INFO: Using Python library c:\development\projects\program-name\.venv\scripts\python37.dll
38777 INFO: Found binding redirects:
[]
38785 INFO: Warnings written to C:\Development\projects\program-name\exe\programname\warn-programname.txt
38876 INFO: Graph cross-reference written to C:\Development\projects\program-name\exe\programname\xref-programname.html
38898 INFO: checking PYZ
38898 INFO: Building PYZ because PYZ-00.toc is non existent
38898 INFO: Building PYZ (ZlibArchive) C:\Development\projects\program-name\exe\programname\PYZ-00.pyz
40092 INFO: Building PYZ (ZlibArchive) C:\Development\projects\program-name\exe\programname\PYZ-00.pyz completed successfully.
40111 INFO: checking PKG
40111 INFO: Building PKG because PKG-00.toc is non existent
40112 INFO: Building PKG (CArchive) PKG-00.pkg
40959 WARNING: One binary added with two internal names.
40959 WARNING: ('libGLESv2.dll',
 'C:\\development\\projects\\program-name\\.venv\\lib\\site-packages\\PyQt5\\Qt\\bin\\libGLESv2.dll',
 'BINARY')
40959 WARNING: was placed previously at
40959 WARNING: ('PyQt5\\Qt\\bin\\libGLESv2.dll',
 'C:\\development\\projects\\program-name\\.venv\\lib\\site-packages\\PyQt5\\Qt\\bin\\libGLESv2.dll',
 'BINARY')
49925 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
49930 INFO: Bootloader c:\development\projects\program-name\.venv\lib\site-packages\PyInstaller\bootloader\Windows-32bit\runw.exe
49930 INFO: checking EXE
49931 INFO: Building EXE because EXE-00.toc is non existent
49931 INFO: Building EXE from EXE-00.toc
49934 INFO: Copying icons from ['C:\\Development\\projects\\program-name\\programname\\gui\\icon.ico']
49935 INFO: Writing RT_GROUP_ICON 0 resource with 90 bytes
49935 INFO: Writing RT_ICON 1 resource with 21761 bytes
49935 INFO: Writing RT_ICON 2 resource with 67624 bytes
49935 INFO: Writing RT_ICON 3 resource with 9640 bytes
49936 INFO: Writing RT_ICON 4 resource with 4264 bytes
49936 INFO: Writing RT_ICON 5 resource with 2440 bytes
49936 INFO: Writing RT_ICON 6 resource with 1128 bytes
49941 INFO: Updating manifest in C:\Users\user\AppData\Local\Temp\tmp2yg11lck
49959 INFO: Updating resource type 24 name 1 language 0
49961 INFO: Appending archive to EXE C:\Development\projects\program-name\exe\programname.exe
50086 INFO: Building EXE from EXE-00.toc completed successfully.
```


... And when running with the --hidden-import flag i get the same output with a slightly different warning message:
```
10176 WARNING: Hidden import "sip" not found!
```

**Comment by altendky** [comment]
https://github.com/pyinstaller/pyinstaller/blob/v3.5/PyInstaller/hooks/hook-PyQt5.py#L15-L21

For the warning about not finding `sip`, I'm thinking that's just 'normal'.  In the above source they blindly look for both `sip` and `PyQt5.sip`.  Also, it shows up in my build logs.  My suggestion of specifying the hidden import seems to be irrelevant.

Any chance you are interested enough to make up a sample project that you could share?  Given the redactions above I'm assuming you can't share your actual project.

Is the program you launched that does not work one of the pyqt5-tools wrappers?  Or is it your application?

**Comment by meichthys** [comment]
Unfortunately I can't share my project, but i may be able to put together a hello world program that would exhibit the same issue. The program that does not work is my own application, not a pyqt5-tools wrapper. 

I'll check on my working builds to see if i also get the sip warning. It's possible I do and just never noticed.

**Comment by altendky** [comment]
So you pyinstaller your program and it doesn't work.  But you have pyinstaller include pyqt5-tools and the result fails, but if you don't have pyinstaller include pyqt5-tools then your program works?  What part of pyqt5-tools do you use in your own program?

**Comment by meichthys** [comment]
I just let pyinstaller do it's thing by auto-detecting dependencies to bundle with the executable. I guess I never really checked to see what it is actually including. Now that I'm thinking about it, it might not be including pyqt5-tools at all since all the import statements in the program reference pyqt directly. So in the end, it sounds like it might be an upstream issue with the new version of PyQt, but it is a little strange then that v5.12.3.1.5 doesn't work if it was still using the same PyQt version as v5.12.1.1.5rc4 that does work.

**Comment by altendky** [comment]
It's not, the first three version places are PyQt5, the last three are pyqt5-tools.

Looks like I'm still using PyQt5.11.2 in both my applications (I should fix that...).  I'll try latest tomorrow.

I guess I'm still not clear what the actual working and failing scenarios are.  Do `pip freeze` in both cases.  Maybe try without pyqt5-tools and then with various PyQt5 versions.  Also maybe try with latest pyinstaller from GitHub.  But sure, if you make an example project I can build and share your working and failing `pip freeze` output for it I'll take a peek.

**Comment by meichthys** [comment]
Ok, thanks for the input. I'll play around with different PyQt versions tomorrow to see if i can pinpoint the issue to a specific PyQt version.

**Comment by altendky** [comment]
I'm guessing that when you install pyqt5-tools it is changing your PyQt5 version and...

https://github.com/pyinstaller/pyinstaller/issues/4293

**Comment by meichthys** [comment]
Ah, yes, that pyinstaller issue definitely seems relevant. Thanks for finding that. I'm not sure why i didn't come across that earlier! I'm going to go ahead and close this issue since it seems highly likely that the issue you referenced is what i'm facing.

Thanks again, and great work on pyqt5-tools!

**Comment by altendky** [comment]
I usually end up installing pyinstaller from git not pypi...  :[  Let me know how it works out. I'll update my stuff tomorrow and see what happens.

**Comment by altendky** [comment]
Recreates the issue: https://ci.appveyor.com/project/KyleAltendorf/pm/builds/26858236
Resolves the issue: https://ci.appveyor.com/project/KyleAltendorf/pm/builds/26861440

Each should link to source commits, have a downloadable .zip artifact, show the versions used in `pip freeze` in the log, etc.  I just grabbed latest git pyinstaller.

**Comment by meichthys** [comment]
Thanks for the appveyor posts. I can confirm the same thing. Using the pyinstaller version listed in the first appveyor log, my program fails too, but when using the pyinstaller version listed in the second appveyor log, my program runs without issue. I guess I'll have to wait until pypi gets updated or use the github version.

Thanks for your tests on this!
