### ISSUE TITLE
Cannot install pyqt5-tools via pip

### ISSUE THREAD

**Issue by ShowNadda** [altendky/pyqt5-tools#36]
I cannot install the pyqt5-tools via pip. I first tried normally, and then after reading your suggestion for the other person, I setup virtualenv, and had pyqt successfully install there (as opposed to where I already had it installed, so I know I set this up right) However, the pyqt-tools don't.
I am on Windows 10 if it helps.

**Comment by ralbra** [comment]
If you are on python 3.8 see #35

**Comment by altendky** [comment]
@ShowNadda if @ralbra's answer doesn't cover you, please provide some more information.  Usually a copy of your terminal session showing what command you are running and the full output along with something showing your python version etc is good.

**Comment by altendky** [comment]
If you had an issue other than #35, feel free to reopen and add more information.
