### ISSUE TITLE
cannot successfully install pyqt5-tools

### ISSUE THREAD

**Issue by WilburZiWong** [altendky/pyqt5-tools#38]
I have tried to install pyqt5-tools in the command line using 'pip install pyqt5-tools' and in Pycharm. But the results are the same, they appeared an error occurring that **'UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 2597: illegal multibyte sequence'**. Later I would show the whole command output information.

**Comment by WilburZiWong** [comment]
Collecting pyqt5-tools
  Using cached https://files.pythonhosted.org/packages/15/ff/46d8d9fd3bf64bfa1e4cdc8a88b547d0e947c952b831a058ca961b1f2543/pyqt5_tools-5.13.0.1.5-cp36-none-win_amd64.whl
Collecting python-dotenv (from pyqt5-tools)
  Using cached https://files.pythonhosted.org/packages/65/16/43f00b087c7f3f20a8d8dc16d6f6e2eff4e662afcb31ec4a31535a5be244/python-dotenv-0.10.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\wangzixuan\AppData\Local\Temp\pycharm-packaging\python-dotenv\setup.py", line 13, in <module>
        long_description = read_files(['README.md', 'CHANGELOG.md'])
      File "C:\Users\wangzixuan\AppData\Local\Temp\pycharm-packaging\python-dotenv\setup.py", line 9, in read_files
        data.append(f.read())
    UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 2597: illegal multibyte sequence
    
    ----------------------------------------

Command "python setup.py egg_info" failed with error code 1 in C:\Users\wangzixuan\AppData\Local\Temp\pycharm-packaging\python-dotenv\

**Comment by WilburZiWong** [comment]
Wow! Your solution addressed my problem so quickly. Many thanks!

**Comment by altendky** [comment]
The fix was released on February 7, 2020.

https://pypi.org/project/python-dotenv/#history
