### ISSUE TITLE
pylupdate5 cause UnicodeEncodeError: 'latin-1' codec can't encode

### ISSUE THREAD

**Issue by vba34520** [altendky/pyqt5-tools#45]
Python version: 3.6.4
PyQt5 version: 5.13.0
pyqt5-tools version: 5.13.0.1.5

I use `pylupdate5 test.py -ts zh_CN.ts`, but it cause `UnicodeEncodeError: 'latin-1' codec can't encode characters in position 12-14: ordinal not in range(256)`

test.py
```python
# -*- coding: utf-8 -*-
import sys
from PyQt5.QtCore import QRect
from PyQt5.QtWidgets import QMainWindow, QApplication, QPushButton, QDialog


class Mwindow(QDialog):
    def __init__(self):
        super(Mwindow, self).__init__()
        self.resize(100, 60)
        self.down1 = QPushButton(self.tr('download'), self)
        self.down1.setGeometry(QRect(10, 5, 90, 23))

        self.down2 = QPushButton(self.tr('upload'), self)
        self.down2.setGeometry(QRect(10, 30, 90, 23))


if __name__ == '__main__':
    app = QApplication(sys.argv)
    mainWin = Mwindow()
    mainWin.show()
    sys.exit(app.exec_())
```

Thank you for your work!

**Comment by altendky** [comment]
My apologies, apparently I completely missed this question.  Were you able to actually resolve it?

**Comment by Koi-foo** [comment]
I am new to python.
Also ran into this problem.

**Comment by WC12366** [comment]
the path to your py file cannot contain non-ascii chars

**Comment by altendky** [comment]
@WC12366, that seems like a thing worth reporting on the maillist.  Unless it is actually an issue in the code here?  I haven't seen a full traceback so I'm not clear.

https://www.riverbankcomputing.com/mailman/listinfo/pyqt

**Comment by WC12366** [comment]
here's the full traceback if the path contains non-ascii characters:
```
Traceback (most recent call last):
  File "c:\program files\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python38\Scripts\pylupdate5.exe\__main__.py", line 7, in <module>
  File "c:\program files\python38\lib\site-packages\PyQt5\pylupdate_main.py", line 223, in main
    fetchtr_py(fi.absoluteFilePath(), fetchedTor,
UnicodeEncodeError: 'latin-1' codec can't encode characters in position xx-xx: ordinal not in range(256)
```

**Comment by WC12366** [comment]
xx-xx is the the beginning and the ending position of non-ascii substring in the path

**Comment by WC12366** [comment]
for me, add `.encode('gbk')` to line 224 solve this problem, but somehow, there will be a pylupdate5 error: Cannot open Python source file <path_to_your_py>: Illegal byte sequence if you use `.encode('utf-8')`

**Comment by WC12366** [comment]
changing `fi.absoluteFilePath()` in line 224 and 228 of `<path_to_your_python>\lib\site-packages\PyQt5\pylupdate_main.py` to `fi.absoluteFilePath().encode(locale.getdefaultlocale()[1]` solves this problem (also import locale at the first line)

**Comment by WC12366** [comment]
@altendky

**Comment by WC12366** [comment]
It seems that it's not an issue in the code here, but it's a issue in `<path_to_your_python>\lib\site-packages\PyQt5\pylupdate_main.py` line 224 and 228

**Comment by WC12366** [comment]
It seems that it's not an issue in the code here, but it's a issue in `<path_to_your_python>\lib\site-packages\PyQt5\pylupdate_main.py` line 224 and 228

**Comment by Koi-foo** [comment]
> путь к вашему файлу py не может содержать символы, отличные от ascii

Thank you very much.
I figured it out too. Just changed the path.
This is an obvious newbie mistake. An experienced person will not make such a mistake. :-)

**Comment by altendky** [comment]
Well, I don't know if the locale encoding or UTF-8 would be better, or maybe using `os.fsencode()`, but...  I just passed this on to the maillist.  Thanks for the extra details.

https://www.riverbankcomputing.com/pipermail/pyqt/2021-January/043575.html

@Koi-foo generally speaking you should be able to use non-ascii characters in your file names.  It certainly does get more hazardous and programs do have to be careful what they do.  But, I think this is the basic case that the controversial surrogate pairs in Python encoding are for.  You can decode file names which may have arbitrary bytes in them, store them in a string, then re-encode them to the get back to filesystem bytes.  But, Python does this itself.  If you do anything else with the string you have to be wary as  it won't be generally encodable.

**Comment by WC12366** [comment]
@altendky Using UTF-8 can't fix this, because pylupdate5 will decode the path as the default encoding of os. If the default encoding is gbk, you will get a invalid byte sequence error.

**Comment by altendky** [comment]
Yeah, as I thought more about it it does seem to be a matter of \_not\_ encoding and decoding in the normal path and using `os.fsencode()` and `os.fsdecode()` when you must.  But, I didn't actually pull up the code to read it and likely I'll just leave this to Phil to figure out.

**Comment by altendky** [comment]
https://www.riverbankcomputing.com/pipermail/pyqt/2021-January/043576.html
> The suggested fix has been applied in the next snapshot.
>
> Phil
