### ISSUE TITLE
Error starting Designer in new release 

### ISSUE THREAD

**Issue by NHades** [altendky/pyqt5-tools#54]
Just upgraded to version  pyqt5-tools-5.15.1.1.7.3
Now I can't start Designer and get this error message

![error](https://user-images.githubusercontent.com/6215392/94368123-9b056c00-00b0-11eb-9d9f-a3deaf46e142.png)

I uninstalled, and reinstalled, still same error.

**Comment by altendky** [comment]
How are you launching Designer?  What was the last version that worked for you?

**Comment by NHades** [comment]
I get the error when I started from:

..\Lib\site-packages\pyqt5_tools\Qt\bin\designer.exe

However, when I started from:
..\Scripts\designer.exe

No error occurs.

**Comment by altendky** [comment]
Yes, do not dig down into site-packages.  Use the generated scripts.  Also consider `pyqt5designer.exe` and have a look through [the readme](https://github.com/altendky/pyqt5-tools#usage).  The generated wrappers in `env/scripts/` (or `env/bin/` in LInux) setup the environment such that the raw Qt `.exe` files will work.
