### ISSUE TITLE
The library will not be installed in Python 3.9

### ISSUE THREAD

**Issue by GoodPal** [altendky/pyqt5-tools#65]
Hello
Thanks for your awesome library
But this version is not installed in Python version 3.9   on windows 10

ERROR: Could not find a version that satisfies the requirement pyqt5-tools (from versions: none)
ERROR: No matching distribution found for pyqt5-tools

**Comment by altendky** [comment]
See #59 (and #58 for why 3.9 wheels aren't published to PyPI).
