### ISSUE TITLE
openpyxl - how to rotate an image in a workbook

### ISSUE THREAD

**Issue by Admund20** [altendky/pyqt5-tools#69]
Is there a way to rotate an image in a workbook? I can adjust the width and height of it but no rotational attributes in the Image object. Thank you

**Comment by altendky** [comment]
Sounds like a question for either https://foss.heptapod.net/openpyxl/openpyxl/-/issues or maybe [#python](https://www.python.org/community/irc/)?  FYI, some places like to keep their issue trackers for issues rather than help.  I don't know where openpyxl stands on that front.

**Comment by Admund20** [comment]
Ok, thank you for the info.
