### ISSUE TITLE
Unable to 'view code' from Designer

### ISSUE THREAD

**Issue by altendky** [altendky/pyqt5-tools#7]
![image](https://user-images.githubusercontent.com/543719/27794721-4c30e6fa-5fd1-11e7-8d35-abb3f3068308.png)

It seems that the directory structure isn't quite acceptable for Designer to find the uic executable.

**Comment by altendky** [comment]
Looks like this is the line that makes the path.

```
const QString binary = QLibraryInfo::location(QLibraryInfo::BinariesPath) + QStringLiteral("/uic");
```
https://github.com/qt/qttools/blob/41bb420ec19b67a1716d6fa3612f538fdcb18c22/src/designer/src/lib/shared/qdesigner_utils.cpp#L718

If all the Qt files are moved into a `bin` subdirectory Designer still looks another layer down into another `bin` directory for `uic.exe`.  It seems that the underlying lookup is, in a sense, identifying the sysroot one layer too low.

https://github.com/qt/qtbase/blob/f57322f70e019a252d9846e4b3103b5a28b0d243/src/corelib/global/qlibraryinfo.cpp#L447

**Comment by altendky** [comment]
It might be nifty to make it so that this called `pyuic` instead.  I would think it wouldn't be too difficult to make an installed script that would pass along to pyuic if installed.

**Comment by BUAA-CFan** [comment]
I found this problem,too.But I do not know how to config the path of uic.exe
I tried to solve like this:
1. Creat a folder named "bin" in your pyqt5-tools root folder
2.Copy all the files and folders of your pyqt5-tools root folder to "bin" folder (I do this because I don't know exactly whick file or folder uic need, it looks so stupid but it dose work!)
Now view code works normally......

**Comment by altendky** [comment]
@BUAA-CFan, you did this with uic.exe to generate C++ code?  Or with pyuic5.exe?

**Comment by altendky** [comment]
I also don't bother with pyuic5 and instead just uic.loadUi() in my code.  That way I don't have to remember to do the extra conversion step.

**Comment by BUAA-CFan** [comment]
@altendky  No，I use this designer to design my form and transfer the ui file into python code using pyuic. I'm new to Qt. At first I didn't know that this "View code" is for showing C++ code, I thought I could see the python code in the designer and could change the form by modifying python code, like designing winform using visual stuido. But after I solved this problem I found that this is for C++ code. So, it dosen't bother me now.

**Comment by billhayes** [comment]
I tried BUAA-CFan's method and it works.
I actually only copied the files from pyqt5-tools directory (none of the the folders, and I also removed all of the .exe files except the uic.exe.  That leave mostly .dll's.

**Comment by jsuria** [comment]
BUAA-CFan's solution also worked me, though YMMV:

1. Created a bin subfolder.
2. Created a "shortcut" to uic.exe inside bin. ( I used a Mingw64 terminal to run "ln -s")
3. Tried the "View Code" action in designer and it works!

**Comment by altendky** [comment]
I'm still confused why we want to see c code.

**Comment by billhayes** [comment]
I like to see the code that generates the layout.  At some point I may want to create the code by hand so that I can directly edit it.

**Comment by altendky** [comment]
@billhayes, pyuic5 would give you actual Python code.  Wouldn't you prefer that?

**Comment by billhayes** [comment]
Yes, now that you mention it, that's the way I usually do it, though it takes a few more steps.

**Comment by altendky** [comment]
I added in latest build a script you can run after installing pyqt5-tools (also requires pyqt5 to already be installed) to copy the pyuic5.exe to where Designer is looking for uic.exe and you should get generated Python code shown when you Form > View Code.

**Comment by altendky** [comment]
err...  the script would be at `Scripts\pyqt5toolsinstalluic`.

**Comment by altendky** [comment]
v1.3 released: https://www.riverbankcomputing.com/pipermail/pyqt/2018-September/040940.html

**Comment by Sotime1150** [comment]
![sss](https://user-images.githubusercontent.com/43653088/47597005-5cbe1a00-d97a-11e8-9db4-ac148f2f22f2.PNG)
